# Generated by Django 4.2.26 on 2025-11-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.CharField(blank=True, help_text='Track duration (e.g., 4:44)', max_length=10, null=True),
        ),
    ]
