# Generated by Django 4.2.26 on 2025-11-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_track_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='contact',
        ),
        migrations.AddField(
            model_name='artist',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
