# Generated by Django 4.2.26 on 2025-11-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_artist_contact_artist_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='email',
            field=models.EmailField(default='noreply@example.com', max_length=254),
        ),
    ]
