# Generated by Django 4.2.26 on 2025-12-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0005_album_slug_artist_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="quick_facts",
            field=models.JSONField(blank=True, help_text="Quick facts about the artist (JSON format)", null=True),
        ),
    ]
