# Generated by Django 4.2.26 on 2025-12-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0006_artist_quick_facts"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="featured_at",
            field=models.DateTimeField(
                blank=True, help_text="When this album was featured", null=True
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Mark as featured on homepage"
            ),
        ),
    ]
