# Generated by Django 4.2.26 on 2026-01-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0007_album_featured_at_album_is_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="slug",
            field=models.SlugField(blank=True, max_length=70),
        ),
    ]
